services:

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: db_mysql
    restart: always
    tty: true
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    container_name: db_adminer
    ports:
      - 9000:9000