version: '3.3'

services:
  db:
    image: mysql:8
    container_name: db_mysql
    restart: always
    tty: true
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loja_db
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci', '--default-authentication-plugin=mysql_native_password']

  adminer:
    image: adminer
    restart: always
    container_name: db_adminer
    ports:
      - 9000:9000