version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes: 
      - ./DB:/var/lib/postgresql/data
volumes:
  db:
    driver: local